kabbage/common/urls.py
from django.conf.urls import patterns, url
from .views import IndexView, SearchFormView


urlpatterns = patterns(
    '',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^search/$', SearchFormView.as_view(), name='search'),
)

kabbage/kabbage/urls.py
from django.conf.urls import patterns, include, url, static
from django.conf import settings
from django.contrib import admin

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('common.urls', namespace='common')),
)


if settings.DEBUG:
    urlpatterns += static.static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kabbage/common/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

SEARCH_CHOICES = (
    ('T', 'Twitter'),
    ('W', 'Wikipedia'),
)


class SearchForm(forms.Form):
    search_criteria = forms.MultipleChoiceField(
        label=_('Sites available'),
        choices=SEARCH_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    query = forms.CharField(
        max_length=100,
        label=_('Search'),
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.add_placeholder(
            self.fields['query'],
            _('Insert your search here'))

    def add_placeholder(self, field, placeholder):
        field.widget.attrs['placeholder'] = placeholder

kabbage/common/views.py
from requests import ConnectionError
import twython
import wikipedia
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import FormView, TemplateView
from .forms import SearchForm

# Create your views here.


class IndexView(TemplateView):
    template_name = 'common/index.html'


class SearchFormView(FormView):
    form_class = SearchForm
    template_name = 'common/search.html'
    error_message = 'There was an error in the search'

    def get(self, request, *args, **kwargs):
        self.context = {}
        self.page_twitter = request.GET.get('page_twitter')
        self.page_wikipedia = request.GET.get('page_wikipedia')
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if 'query' in request.GET:
            query = request.GET.get('query')
            form = SearchForm(request.GET)
            self.context['query'] = query
            if 'search_criteria' in request.GET:
                sc = request.GET.getlist('search_criteria')
                self.get_data(query, 'T' in sc, 'W' in sc)
        self.context['form'] = form
        return self.render_to_response(self.get_context_data(**self.context))

    def get_page(self, page, objects):
        paginator = Paginator(objects, 10)
        try:
            objects = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            objects = paginator.page(1)
        except EmptyPage:
            # If page is out of range, deliver last page of results.
            objects = paginator.page(paginator.num_pages)
        return objects

    def get_data(self, query, search_twitter, search_wikipedia):
        if search_twitter:
            self.get_twitter_data(query)
        if search_wikipedia:
            self.get_wikipedia_data(query)

    def get_twitter_data(self, query):
        self.context['sct'] = True
        self.context['page_twitter'] = self.page_twitter
        twitter_api = twython.Twython(
            settings.TWITTER_API_KEY,
            access_token=settings.TWITTER_ACCESS_TOKEN
        )
        try:
            self.context['twitter_results'] = twitter_api.search(
                q=query, count=100)['statuses']
            self.context['twitter_results'] = self.get_page(
                self.page_twitter, self.context['twitter_results']
            )
        except twython.TwythonAuthError:
            self.context['twitter_error'] = 'Twitter API authentication error'
        except twython.TwythonRateLimitError:
            self.context['twitter_error'] = 'Rate limit error: Please wait before searching again'
        except twython.TwythonError:
            self.context['twitter_error'] = 'Connection Error'

    def get_wikipedia_data(self, query):
        self.context['scw'] = True
        self.context['page_wikipedia'] = self.page_wikipedia
        try:
            self.context['wikipedia_results'] = wikipedia.search(query, results=100)
            self.context['wikipedia_results'] = self.get_page(
                self.page_wikipedia, self.context['wikipedia_results'])
        except (wikipedia.HTTPTimeoutError, ConnectionError):
            self.context['wikipedia_error'] = "Wikipedia is not responding"

kabbage/common/templates/common/base.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Kabbage{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'common/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'common/css/common.css' %}">
        <script src="{% static 'common/js/vendor/modernizr.min.js' %}"></script>
        {% block extra-head-tags %}{% endblock %}
    </head>
    <body>

        {% include 'common/navigation_bar.html' %}

        {% block content %}{% endblock %}

        <script src="{% static 'common/js/vendor/jquery.min.js' %}"></script>
        <script src="{% static 'common/js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'common/js/plugins.js' %}"></script>
        {% block extra-script-tags %}{% endblock %}
    </body>
</html>

kabbage/common/templates/common/index.html
{% extends 'common/base.html' %}
{% load i18n %}
{% block content %}

<div class="container">
    <div class="jumbotron">
        <div class="container">
            <h1>Kabbage test!</h1>
            <p>{% trans "As a Kabbage developer, I want to see how you code a lightweight application, so that I can get a feel for a your skills and strengths." %}</p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'common:search' %}" role="button">Search</a></p>
        </div><!-- container -->
    </div><!-- jumbotron -->
</div><!-- container -->

{% endblock %}

kabbage/common/templates/common/navigation_bar.html
{% load i18n %}
<div id="navigation-bar" class="container">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button><!-- navbar-toggle -->
            <a class="navbar-brand" href="{% url 'common:index' %}">Kabbage</a>
        </div><!-- navbar-header -->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form class="navbar-form" action="{% url 'common:search' %}" method="get">
                        <div class="form-group">
                            <input 
                                type="text" class="form-control"
                                required="true" name="query"
                                placeholder="Enter your search here">
                            <input type="hidden" name="search_criteria" value="T">
                            <input type="hidden" name="search_criteria" value="W">
                        </div>
                        <button type="submit" class="btn btn-default">{% trans "Search" %}</button>
                    </form>
                </li>
            </ul><!-- navbar-nav -->
        </div><!-- nav-collapse -->
    </div><!-- navbar -->
</div><!-- container -->

kabbage/common/templates/common/search.html
{% extends 'common/base.html' %}
{% load bootstrap3 %}
{% load i18n %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1>{% trans "Search" %}</h1>
            <form action="{% url 'common:search' %}" method="get">
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" class="btn btn-success">{% trans "Search results" %}</button>
                {% endbuttons %}
            </form>
        </div><!-- col-md -->
    </div><!-- row -->
    {% include 'common/search_results.html' %}
</div><!-- container -->

{% endblock %}

kabbage/common/templates/common/search_results.html
{% load i18n %}
<div class="col-md-8">
    {% if twitter_error %}
        <div class="alert alert-danger">
            {% trans twitter_error %}
        </div>
    {% else %}
    	<h1>{% trans "Twitter results" %}</h1>
        <div class="list-group>">
            {% for result in twitter_results %}
                <li>
                    <div class="list-group-item">
                        <p>
                            <img src="{{ result.user.profile_image_url }}"/>
                            <strong>{{ result.user.name }}</strong>
                        </p>
                        <a href="https://twitter.com/statuses/{{ result.id_str }}" target="_blank">{{ result.text }}</a>
                    </div>
                </li>
            {% empty %}
                <div class="alert alert-warning">
                    <p>{% trans "No Twitter results" %}</p>
                </div>
            {% endfor %}
        </div>
        <nav>
            <ul class="pagination">
                <li>
                    {% if twitter_results.has_previous %}
                        <a href="?query={{ query }}&{% if sct %}search_criteria=T&{% endif %}{% if scw %}search_criteria=W&{% endif %}{% if page_wikipedia %}page_wikipedia={{ page_wikipedia }}&{% endif %}page_twitter={{ twitter_results.previous_page_number }}">{% trans "previous" %}</a>
                    {% endif %}
                </li>

                <li>
                    <span class="current">
                        {% trans Page %} {{ twitter_results.number }} {% trans "of" %} {{ twitter_results.paginator.num_pages }}.
                    </span>
                </li>
                
                <li>
                   {% if twitter_results.has_next %}
                    <a href="
                        ?query={{ query }}&{% if sct %}search_criteria=T&{% endif %}{% if scw %}search_criteria=W&{% endif %}{% if page_wikipedia %}page_wikipedia={{ page_wikipedia }}&{% endif %}page_twitter={{ twitter_results.next_page_number }}">
                        {% trans "next" %}</a>
                {% endif %}
                </li>
            </ul>
        </nav>
    {% endif %}
</div>


<div class="col-md-6">
    {% if wikipedia_error %}
        <div class="alert alert-danger">
            {% trans wikipedia_error %}
        </div>
    {% else %}
        <h1>{% trans "Wikipedia results" %}</h1>
        <div class="list-group">
            {% for result in wikipedia_results %}
                <li>
                    <a class="list-group-item" href="https://en.wikipedia.org/wiki/{{ result|iriencode }}" 
                        target="_blank">
                        {{ result }}
                    </a>
                </li>
            {% empty %}
                <div class="alert alert-warning">
                    <p>{% trans "No Wikipedia results" %}</p>
                </div>
            {% endfor %}
        </div>
    <nav>
        <ul class="pagination">
            <li>
                {% if wikipedia_results.has_previous %}
                    <a href="?query={{ query }}&{% if sct %}search_criteria=T&{% endif %}{% if scw %}search_criteria=W&{% endif %}{% if page_twitter %}page_twitter={{ page_twitter }}&{% endif %}page_wikipedia={{ wikipedia_results.previous_page_number }}">{% trans "previous" %}</a>
                {% endif %}
            </li>

            <li>
                <span class="current">
                    {% trans Page %} {{ wikipedia_results.number }} {% trans "of" %} {{ wikipedia_results.paginator.num_pages }}.
                </span>
            </li>
            
            <li>
               {% if wikipedia_results.has_next %}
                <a href="
                    ?query={{ query }}&{% if sct %}search_criteria=T&{% endif %}{% if scw %}search_criteria=W&{% endif %}{% if page_twitter %}page_twitter={{ page_twitter }}&{% endif %}page_wikipedia={{ wikipedia_results.next_page_number }}">
                    {% trans "next" %}</a>
            {% endif %}
            </li>
        </ul>
    </nav>
    {% endif %}
</div>